name: Crowdshuttle-Dev

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: change directory and restart the pipeline
        run: | 
          cd backend
          git pull origin main
          pm2 restart 0
