name: Crowdshuttle-Dev

on:
  push:
    branches:
      -master
jobs:
  build:
    steps:
      - uses: actions/checkout@v2
      - name: change directory and restart the pipeline
        run: | 
          cd backend
          git pull origin main
          pm2 restart 0
