name: CI

on:
  workflow_dispatch:
  push:
    branches:
      -master
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: change directory
        run: | 
          cd backend
          node -v
          git --version
